### ISSUE TITLE
The specified checksum type is not supported by Vagrant: SHA256

### ISSUE THREAD

**Issue by maxkratz** [gusztavvargadr/packer#444]
Our weekly scheduled CI runs on Monday morning. Today, all of our vagrant-based CIs failed because of this error:

```
[...]
Progress: 96% (Rate: 54.5M/s, Estimated time remaining: 0:00:02)
Progress: 98% (Rate: 54.5M/s, Estimated time remaining: 0:00:01)
    edgedb: Calculating and comparing box checksum...
The specified checksum type is not supported by Vagrant: SHA256.
Vagrant supports the following checksum types:
md5, sha1, sha256, sha3[84](https://github.com/maxkratz/edgedb-vm/actions/runs/9639698210/job/26583783769#step:7:85), sha512
Error: Process completed with exit code 1.
```

Examples:
- https://github.com/eMoflon/emoflon-ibex-vm/actions/runs/9639693983/job/26582942188
- https://github.com/maxkratz/edgedb-vm/actions/runs/9639698210/job/26583783769

On the [vagrant cloud](https://portal.cloud.hashicorp.com/vagrant/discover/gusztavvargadr/xubuntu-desktop-2404-lts), I saw that there were newly released versions of your vagrant images.
Do you have any idea how I can fix this error? Thanks.

**Comment by VladAdGad** [comment]
I've met the same problem and I'm going crazy to fix it. I tried to forcefully use 
`vagrant box add --checksum-type=sha256 gusztavvargadr/windows-11`
and
```
Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-11"
    # config.vm.box_download_checksum = "sha256"
    # config.vm.box_download_checksum = ""
    # config.vm.box_version = "2302.0.2404"
  end
```
without a luck

**Comment by jcaselman-keysight** [comment]
I'm seeing this as well with windows-11 2302.0.2404, coming from 2302.0.2312
![image](https://github.com/gusztavvargadr/packer/assets/116232122/bc3da90b-e7ec-4abb-8c86-007c72ad6eb1)


The metadata url for this box shows `SHA256` under checksum type, so I think this will require a change to the publishing from this project to correct?
https://vagrantcloud.com/api/v2/vagrant/gusztavvargadr/windows-11
![image](https://github.com/gusztavvargadr/packer/assets/116232122/ab24832e-1b75-4f5a-a8dd-366d4bcb1ee9)

I am working around this currently by:
* Downloading the metadata json file and replacing `SHA256` with `sha256`
* Hosting it locally by running `python3 -m http.server` in the folder containing the modified metadata file
* modifying the `metadata_url` file at `~/.vagrant.d/boxes/gusztavvargadr-VAGRANTSLASH-windows-11` to point to the local hosted version of the metadata file (for me `http://127.0.0.1:8000/windows-11.json` (make sure there's no whitespace/line endings at the end)

After downloading the box and getting the failure in my first screenshot, I am able to then import it and spin up a derived box using `vagrant up` with the above in place with a `Vagrantfile` like
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11"
end
```

@gusztavvargadr I'm happy to put in a PR with some direction but I do not see where this uppercased `SHA256` is coming from.  I see lowercased version in a few places in the templates :confused:

**Comment by maxkratz** [comment]
> @gusztavvargadr I'm happy to put in a PR with some direction but I do not see where this uppercased `SHA256` is coming from. I see lowercased version in a few places in the templates 😕

I think that this error does not necessarily come from a change in this repository. The latest change in the repo is from 2024-06-09 and one of our projects has had successful CI runs (that pull and use one of the VMs provided by this repo) after that:
- https://github.com/eMoflon/emoflon-ibex-vm/actions

Our first failed run is from 2024-06-24 (Monday this week).

**Comment by jcaselman-keysight** [comment]
> > @gusztavvargadr I'm happy to put in a PR with some direction but I do not see where this uppercased `SHA256` is coming from. I see lowercased version in a few places in the templates 😕
> 
> I think that this error does not necessarily come from a change in this repository. The latest change in the repo is from 2024-06-09 and one of our projects has had successful CI runs (that pull and use one of the VMs provided by this repo) after that:

That does align with the fact that I'm not able to find a source here.  I have started to suspect that the issue may be somewhere in the azure pipelines referenced here but not visible to us "general public", but this is just speculation

Despite the commit history here, vagrant cloud shows that all of the various windows-11 versions were created 5 days ago:
![image](https://github.com/gusztavvargadr/packer/assets/116232122/ef2e6b77-6c89-4c7b-b624-ee11e5ce7f9b)

And every time I look at the windows-11 box page, it shows it was updated fairly recently (within last several hours):
![image](https://github.com/gusztavvargadr/packer/assets/116232122/ed3efd7d-8d7b-47fd-be65-b32575fbe550)

**Comment by maxkratz** [comment]
> Despite the commit history here, vagrant cloud shows that all of the various windows-11 versions were created 5 days ago:
> 
> [...]
> 
> And every time I look at the windows-11 box page, it shows it was updated fairly recently (within last several hours):

You are correct, I also saw the new versions of the boxes pop up right before our pipelines failed.

I'm curious what the error is at the end :)

**Comment by gusztavvargadr** [comment]
Hi all,

Thanks for reporting the issues and sorry for the delayed response.

I can confirm I have not released any new versions of the boxes since about 2 months, was just planning to do a new round. However, I have migrated the boxes to HCP Vagrant Registry in the meantime: https://developer.hashicorp.com/vagrant/vagrant-cloud/hcp-vagrant/migration-guide

I suspect this might have caused the issues. Will look into this in more detail and get back to you.

**Comment by gusztavvargadr** [comment]
I have now manually updated all the latest versions of my boxes and removed the checksums from all providers. This should solve the problem for now.

I am doing some basic tests as well, but please try the box downloads again and let me know.

**Comment by ponces** [comment]
> I have now manually updated all the latest versions of my boxes and removed the checksums from all providers. This should solve the problem for now.
> 
> I am doing some basic tests as well, but please try the box downloads again and let me know.

All good here with `gusztavvargadr/windows-10`.
Thanks!

**Comment by jcaselman-keysight** [comment]
windows-11 also working for me now

**Comment by maxkratz** [comment]
> I am doing some basic tests as well, but please try the box downloads again and let me know.

All of our CI pipelines (that use your boxes) are succeeding again. Thank you for the fix.

**Comment by PaulNacamuli** [comment]
@gusztavvargadr 

I have the need to pull down windows-11 / 2302.0.2312 and the issue still exists; noting that you have done the most recent releases.  I believe we are waiting for an update to vagrant to make older builds possible again.

**Comment by gusztavvargadr** [comment]
@PaulNacamuli I have removed now the checksums for that earlier version too, I can remove it for additional versions as well, if you specify them, just wanted to unblock first the majority of the use cases, getting the latest versions.

Btw, I usually remove the versions regularly which are older than 6 months, is that policy working for you? Just curious about your use case using older versions.

**Comment by PaulNacamuli** [comment]
@gusztavvargadr

Thank you for that.  I actually downloaded the file using a browser, then used 'vagrant box add ' to add it.   I wasn't sure if there would still be some kind of checksum validation based on metadata.

Thanks for all the effort you put into maintaining these images.  Very helpful!

**Comment by ponces** [comment]
Just to let everyone know that https://github.com/hashicorp/vagrant/issues/13470 was closed as it was solved not only on the server side, but also on vagrant's side _for resiliency_.
